all:
  hosts:
    node1:
      ansible_host: 192.168.20.190
      ip: 192.168.20.190
      access_ip: 192.168.20.190
      ansible_user: dev
      ansible_password: 1
      ansible_become: true
      ansible_become_password: 1
    node2:
      ansible_host: 192.168.20.191
      ip: 192.168.20.191
      access_ip: 192.168.20.191
      ansible_user: dev
      ansible_password: 1
      ansible_become: true
      ansible_become_password: 1
    node3:
      ansible_host: 192.168.20.192
      ip: 192.168.20.192
      access_ip: 192.168.20.192
      ansible_user: dev
      ansible_password: 1
      ansible_become: true
      ansible_become_password: 1
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
